CREATE TABLE issues (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    issue TEXT NOT NULL,
    who TEXT NOT NULL,
    created TEXT NOT NULL,
    status TEXT,
    status_date TEXT,
    reviewed TEXT
);

CREATE TABLE todos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    todo TEXT NOT NULL,
    who TEXT NOT NULL,
    created TEXT NOT NULL,
    due TEXT NOT NULL,
    status TEXT,
    status_date TEXT,
    reviewed TEXT,
    issue INTEGER
        REFERENCES issues(id) ON DELETE SET NULL
);

CREATE TABLE team (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE weeks (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    endOfWeek INTEGER NOT NULL,
    currentWeek TEXT NOT NULL 
);

CREATE TABLE metrics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sort INTEGER NOT NULL,
    status TEXT NOT NULL,
    who TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    metric_type TEXT NOT NULL,
    metric_format TEXT NOT NULL,
    decimals INTEGER NOT NULL,
    created TEXT NOT NULL,
    archived TEXT,
    data TEXT[]
);